# Generated by Django 4.2.25 on 2025-11-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product',
            new_name='product',
        ),
    ]
